sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_takeout
    username: dev
    password: dev123
  # 定义文件上传到 ！阿里云OSS ！的相关配置
  aliyun:
    oss:
      bucket-name: sky-takeout-backend
      endpoint: oss-us-west-1.aliyuncs.com
      #关于OSS支持的Region与Endpoint的对应关系，
      # 请参见https://www.alibabacloud.com/help/zh/oss/user-guide/regions-and-endpoints。
      region: us-west-1
      dir: sky-takeout/  # 文件存储目录